//------------------------------------------------------------------------------
// <auto-generated>
//     Ten kod został wygenerowany przez narzędzie.
//     Wersja wykonawcza:4.0.30319.42000
//
//     Zmiany w tym pliku mogą spowodować nieprawidłowe zachowanie i zostaną utracone, jeśli
//     kod zostanie ponownie wygenerowany.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infrastructure {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.8.1.0")]
    internal sealed partial class Infrastructure : global::System.Configuration.ApplicationSettingsBase {
        
        private static Infrastructure defaultInstance = ((Infrastructure)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Infrastructure())));
        
        public static Infrastructure Default {
            get {
                return defaultInstance;
            }
        }
    }
}
